# Changes here will be overwritten by Copier
_commit: v7.3.0-24-g169e035
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: ''
project_description: Retrieve data from a Logpoint Security information and event
    management (SIEM) system.
project_slug: logpoint
project_type: plugin
pypi: false

